# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

n_singletons <- function(ances) {
    .Call('rncl_n_singletons', PACKAGE = 'rncl', ances)
}

collapse_single_cpp <- function(ances, desc, elen, nnode) {
    .Call('rncl_collapse_single_cpp', PACKAGE = 'rncl', ances, desc, elen, nnode)
}

RNCL <- function(params, paramsVecR) {
    .Call('rncl_RNCL', PACKAGE = 'rncl', params, paramsVecR)
}

